
/*Creacion de la base de datos "La Comanda"*/
    CREATE DATABASE LaComanda;


    /*-- Tabla Empleados --*/
    CREATE TABLE Empleados(
        ID INT AUTO_INCREMENT PRIMARY KEY,
        ROL VARCHAR(50) NOT NULL,
        NOMBRE VARCHAR(255) NOT NULL,
        BAJA BOOLEAN NOT NULL,
        FECHA_ALTA DATE NOT NULL,
        FECHA_BAJA DATE
    );


    /*-- Tabla Mesas --*/
    CREATE TABLE Mesas(
        ID INT AUTO_INCREMENT PRIMARY KEY,
        ESTADO VARCHAR(50) NOT NULL,
        CODIGO_DE_MESA VARCHAR(20) NOT NULL
    );


    /*-- Tabla Productos --*/
    CREATE TABLE Productos(
        ID INT AUTO_INCREMENT PRIMARY KEY,
        SECTOR VARCHAR(50) NOT NULL,
        NOMBRE VARCHAR(255) NOT NULL,
        PRECIO DECIMAL(10,2) NOT NULL,
        TIEMPO_ESTIMADO TIME
    );

    /*-- Tabla Facturaciones --*/
    CREATE TABLE Facturaciones(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_MESA INT NOT NULL,
    FECHA DATE NOT NULL,
    DETALLE VARCHAR(150),
    TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_MESA) REFERENCES Mesas(ID)
    );

    /*-- Tabla Pedidos --*/
    CREATE TABLE Pedidos(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FACTURADO BOOLEAN NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_MESA INT NOT NULL,
    FOTO BLOB,
    TIEMPOESTIMADOTOTAL TIME,
    NOMBRE_CLIENTE VARCHAR(255),
    ID_EMPLEADO INT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES Productos(ID),
    FOREIGN KEY (ID_MESA) REFERENCES Mesas(ID),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES Empleados(ID)
    );
